//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadawaPro1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public int id { get; set; }
        public string subject { get; set; }
        public Nullable<int> marks { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
