//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadawaPro1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        [Key]
        public int id { get; set; }
        [StringLength(100)]

        public string name { get; set; }
        [StringLength(100)]

        public int contact { get; set; }
        [StringLength(100)]

        public string age { get; set; }
        [StringLength(100)]

        public virtual Mark Mark { get; set; }
       
    }
}
